version: '3.4'


services:
  flight-price-predictor:
    container_name: flight-price-predictor
    image: flight-price-predictor
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
        - .env
    environment:
      - MONGO_URI=mongodb://admin:secret@mongodb:27017
    ports:
      - 8000:8000
  mongodb:
    container_name: mongodb
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
